package com.redhat.demos.dm.loan.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Applicant implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Name")
	private java.lang.String name;
	@org.kie.api.definition.type.Label("Credit Score")
	private int creditScore;

	@org.kie.api.definition.type.Label(value = "Gender")
	private java.lang.String gender;

	@org.kie.api.definition.type.Label(value = "Age")
	private int age;

	@org.kie.api.definition.type.Label(value = "Tobaco Consumption")
	private java.lang.Boolean tobacco;

	public Applicant() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public int getCreditScore() {
		return this.creditScore;
	}

	public void setCreditScore(int creditScore) {
		this.creditScore = creditScore;
	}

	public java.lang.String getGender() {
		return this.gender;
	}

	public void setGender(java.lang.String gender) {
		this.gender = gender;
	}

	public int getAge() {
		return this.age;
	}

	public void setAge(int age) {
		this.age = age;
	}

	public java.lang.Boolean getTobacco() {
		return this.tobacco;
	}

	public void setTobacco(java.lang.Boolean tobacco) {
		this.tobacco = tobacco;
	}

	public Applicant(java.lang.String name, int creditScore,
			java.lang.String gender, int age, java.lang.Boolean tobacco) {
		this.name = name;
		this.creditScore = creditScore;
		this.gender = gender;
		this.age = age;
		this.tobacco = tobacco;
	}

}