package com.redhat.demos.dm.loan.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Term implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Amount")
	private int amount;
	@org.kie.api.definition.type.Label("Duration")
	private int duration;
	@org.kie.api.definition.type.Label("Interest Rate")
	private double interestRate;
	@org.kie.api.definition.type.Label("Approved")
	private boolean approved;
	@org.kie.api.definition.type.Label("Reason")
	private String reason;

	@org.kie.api.definition.type.Label(value = "Eligible For Upsell")
	private java.lang.Boolean upsell;

	public Term() {
	}

	public int getAmount() {
		return this.amount;
	}

	public void setAmount(int amount) {
		this.amount = amount;
	}

	public int getDuration() {
		return this.duration;
	}

	public void setDuration(int duration) {
		this.duration = duration;
	}

	public double getInterestRate() {
		return this.interestRate;
	}

	public void setInterestRate(double interestRate) {
		this.interestRate = interestRate;
	}

	public boolean isApproved() {
		return this.approved;
	}

	public void setApproved(boolean approved) {
		this.approved = approved;
	}

	public String getReason() {
		return reason;
	}

	public void setReason(String reason) {
		this.reason = reason;
	}

	public Term(int amount, int duration, double interestRate,
			boolean approved, String reason) {
		super();
		this.amount = amount;
		this.duration = duration;
		this.interestRate = interestRate;
		this.approved = approved;
		this.reason = reason;
	}

	@Override
	public String toString() {
		return String
				.format("Loan [amount=%s, duration=%s, interestRate=%s, approved=%s, reason=%s]",
						amount, duration, interestRate, approved, reason);
	}

	public java.lang.Boolean getUpsell() {
		return this.upsell;
	}

	public void setUpsell(java.lang.Boolean upsell) {
		this.upsell = upsell;
	}

	public Term(int amount, int duration, double interestRate,
			boolean approved, java.lang.String reason, java.lang.Boolean upsell) {
		this.amount = amount;
		this.duration = duration;
		this.interestRate = interestRate;
		this.approved = approved;
		this.reason = reason;
		this.upsell = upsell;
	}

}